In [1]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

In [86]:
i=0
tables=[]
last_page=10
while i <last_page:
    url=f"https://policja.pl/pol/form/1,Informacja-dzienna.html?page={i}"
    response = requests.get(url)
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')
    tables.append(soup.find_all('table'))
    time.sleep(np.ceil(np.random.gamma(1.2, 1.2)))
    print(i)
    i=i+1

0
1
2
3
4
5
6
7
8
9

In [87]:
dfs = []

# Extract data from the table and create a DataFrame

for i in range(len(tables)):
    rows = []
    for row in tables[i][0].find_all('tr')[1:]:  # Skip the header row
        columns = row.find_all('td')
        # print(columns)
        rows.append([col.get_text(strip=True) for col in columns])
    # Define column names
    columns_names = ['Data statystyki', 'Interwencje', 'Zatrzymani na gorącym uczynku', 'Zatrzymani poszukiwani','Kierujący po spożyciu alkoholu','Wypadki drogowe','Zabici w wypadkach','Ranni w wypadkach']

    # Create a Pandas DataFrame
    df = pd.DataFrame(rows, columns=columns_names)
    # Append the DataFrame to the list
    print(i)
    dfs.append(df)

0
1
2
3
4
5
6
7
8
9

In [89]:
dfs[1]

,Data statystyki,Interwencje,Zatrzymani na gorącym uczynku,Zatrzymani poszukiwani,Kierujący po spożyciu alkoholu,Wypadki drogowe,Zabici w wypadkach,Ranni w wypadkach
0,2024-03-17,12256,526,251,259,36,7,47
1,2024-03-16,16486,537,285,272,49,5,55
2,2024-03-15,16996,590,427,197,47,8,48
3,2024-03-14,15509,526,459,167,55,4,60
4,2024-03-13,14505,584,444,207,43,3,43
5,2024-03-12,14425,528,420,186,56,1,69
6,2024-03-11,14533,624,396,320,46,2,55
7,2024-03-10,12979,583,210,337,39,4,53
8,2024-03-09,16529,651,270,401,54,3,61
9,2024-03-08,16170,535,421,264,62,5,71
10,2024-03-07,14436,508,427,156,42,1,43
11,2024-03-06,14024,497,428,179,43,2,48
12,2024-03-05,14099,494,447,175,30,3,32
13,2024-03-04,14583,466,370,238,55,6,67
14,2024-03-03,15907,493,483,199,47,8,48